name: SSH to Local Machine

on:
  push:
    branches:
      - master

jobs:
  generate-keys:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy Private key
        run: |
            mkdir ~/.ssh
            echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: SSH into Local Machine
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p 19384 surya@0.tcp.in.ngrok.io 'cd ~/web_sync && git pull origin master'
